DROP TABLE IF EXISTS stock_movements;
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS batches;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS warehouses;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

-- ROLES (crear primero)
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       code VARCHAR(30) NOT NULL UNIQUE,
                       name VARCHAR(120) NOT NULL
);

-- USERS (con 1 rol)
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(200) NOT NULL UNIQUE,
                       full_name VARCHAR(200) NOT NULL,
                       password_hash VARCHAR(200) NOT NULL,
                       is_active BOOLEAN NOT NULL DEFAULT TRUE,
                       role_id BIGINT NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- PRODUCTS
CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sku VARCHAR(50) UNIQUE,
                          barcode VARCHAR(80) UNIQUE,
                          name VARCHAR(200) NOT NULL,
                          generic_name VARCHAR(200),
                          form VARCHAR(100),
                          strength VARCHAR(100),
                          presentation VARCHAR(120),
                          laboratory VARCHAR(120),
                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- WAREHOUSES
CREATE TABLE warehouses (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            code VARCHAR(50) NOT NULL UNIQUE,
                            name VARCHAR(120) NOT NULL,
                            is_active BOOLEAN NOT NULL DEFAULT TRUE,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- LOCATIONS (opcional)
CREATE TABLE locations (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           warehouse_id BIGINT NOT NULL,
                           code VARCHAR(80) NOT NULL,
                           name VARCHAR(120),
                           is_active BOOLEAN NOT NULL DEFAULT TRUE,
                           created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           CONSTRAINT fk_locations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
                           CONSTRAINT uq_locations_warehouse_code UNIQUE (warehouse_id, code)
);

-- BATCHES
CREATE TABLE batches (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         product_id BIGINT NOT NULL,
                         batch_code VARCHAR(80) NOT NULL,
                         expires_at DATE NOT NULL,
                         manufacturer_ref VARCHAR(120),
                         status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                         notes VARCHAR(500),
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_batches_product FOREIGN KEY (product_id) REFERENCES products(id),
                         CONSTRAINT uq_batches_product_code_exp UNIQUE (product_id, batch_code, expires_at),
                         CONSTRAINT ck_batches_status CHECK (status IN ('ACTIVE','BLOCKED','EXPIRED','DISPOSED'))
);

-- STOCK (location_id nullable)
CREATE TABLE stock (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       warehouse_id BIGINT NOT NULL,
                       batch_id BIGINT NOT NULL,
                       location_id BIGINT,
                       qty_on_hand DECIMAL(18,3) NOT NULL DEFAULT 0,
                       qty_reserved DECIMAL(18,3) NOT NULL DEFAULT 0,
                       min_qty DECIMAL(18,3),
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_stock_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
                       CONSTRAINT fk_stock_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
                       CONSTRAINT fk_stock_location FOREIGN KEY (location_id) REFERENCES locations(id),
                       CONSTRAINT ck_stock_qty_nonneg CHECK (qty_on_hand >= 0 AND qty_reserved >= 0),
                       CONSTRAINT ck_stock_reserved_le_onhand CHECK (qty_reserved <= qty_on_hand)
);

-- Unicidad básica (H2 no soporta partial unique index como Postgres).
-- Para DEV alcanza; en Postgres lo resolvés con índices parciales.
CREATE UNIQUE INDEX uq_stock_wh_batch_loc ON stock (warehouse_id, batch_id, location_id);

-- STOCK MOVEMENTS
CREATE TABLE stock_movements (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 warehouse_id BIGINT NOT NULL,
                                 product_id BIGINT NOT NULL,
                                 batch_id BIGINT NOT NULL,
                                 movement_type VARCHAR(20) NOT NULL,
                                 qty DECIMAL(18,3) NOT NULL,
                                 reason VARCHAR(200) NOT NULL,
                                 reference VARCHAR(200),
                                 notes VARCHAR(500),
                                 from_location_id BIGINT,
                                 to_location_id BIGINT,
                                 performed_by_user_id BIGINT NOT NULL,
                                 occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_mov_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
                                 CONSTRAINT fk_mov_product FOREIGN KEY (product_id) REFERENCES products(id),
                                 CONSTRAINT fk_mov_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
                                 CONSTRAINT fk_mov_from_loc FOREIGN KEY (from_location_id) REFERENCES locations(id),
                                 CONSTRAINT fk_mov_to_loc FOREIGN KEY (to_location_id) REFERENCES locations(id),
                                 CONSTRAINT fk_mov_user FOREIGN KEY (performed_by_user_id) REFERENCES users(id),

                                 CONSTRAINT ck_mov_qty_positive CHECK (qty > 0),
                                 CONSTRAINT ck_mov_type CHECK (movement_type IN ('IN','OUT','ADJUSTMENT','RELOCATION','TRANSFER_IN','TRANSFER_OUT'))
);

CREATE INDEX idx_mov_occurred ON stock_movements (occurred_at);
